FROM node:20-alpine AS build

WORKDIR /app

COPY package.json .
COPY package-lock.json .
RUN apk update
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
CMD [ "nginx", "-g", "daemon off;" ]