stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker compose build
    - docker compose -f tests/docker-compose.yaml build

test-job:
  stage: test
  script:
    - echo "$env" >> .env


    - docker compose -f tests/docker-compose.yaml up --abort-on-container-exit

deploy-job:
  stage: deploy
  script:

    - echo "$env" >> .env
    
    - docker compose down -v
    - rm -rf data

    - docker compose up -d

    - echo "Ждём запуск Postgres..."
    - sleep 5
    - docker exec shortlinker-postgres-1 psql -U $PG_USERNAME -d $PG_DATABASE -f /docker-entrypoint-initdb.d/init.sql