stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker compose build

test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 5 seconds."
    - sleep 5
    - echo "Code coverage is 90%"

deploy-job:
  stage: deploy
  script:

    - echo "PG_APP__DATABASE=$PG_DATABASE" >> .env
    - echo "PG_APP__USERNAME=$PG_USERNAME" >> .env
    - echo "PG_APP__PASSWORD=$PG_PASSWORD" >> .env
    - echo "PG_APP__HOST=$PG_HOST" >> .env
    - echo "PG_APP__PORT=$PG_PORT" >> .env
    - echo "POSTGRES_USER=$PG_USERNAME" >> .env
    - echo "POSTGRES_PASSWORD=$PG_PASSWORD" >> .env
    - echo "POSTGRES_DB=$PG_DATABASE" >> .env
    
    - docker compose down -v

    - docker compose up -d

    - echo "Ждём запуск Postgres..."
    - sleep 5
    - docker exec shortlinker-postgres-1 psql -U $PG_USERNAME -d $PG_DATABASE -f /docker-entrypoint-initdb.d/init.sql